# Ruler Configuration File
# See https://ai.intellectronica.net/ruler for documentation.

# To specify which agents are active by default when --agents is not used,
# uncomment and populate the following line. If omitted, all agents are active.
default_agents = ["claude", "crush", "cline", "cursor", "codex"]

# Enable nested rule loading from nested .ruler directories
# When enabled, ruler will search for and process .ruler directories throughout the project hierarchy
# nested = false

# --- Agent Specific Configurations ---
# You can enable/disable agents and override their default output paths here.
# Use lowercase agent identifiers: amp, copilot, claude, codex, cursor, windsurf, cline, aider, kilocode

[agents.claude]
enabled = true
output_path_instructions = "CLAUDE.md"
output_path_config = ".mcp.json"

[agents.crush]
enabled = true
output_path_instructions = "CRUSH.md"
output_path_config = ".crush.json"

[agents.cline]
enabled = true
output_path_instructions = ".clinerules"

[agents.cursor]
enabled = true
output_path_instructions = ".cursor/rules/ruler_cursor_instructions.mdc"
output_path_config = ".cursor/mcp.json"

# OpenAI Codex CLI agent and MCP config
[agents.codex]
enabled = true
output_path = "AGENTS.md"
output_path_config = ".codex/config.toml"

# Agent-specific MCP configuration for Codex CLI
[agents.codex.mcp]
enabled = true
merge_strategy = "merge"

# [agents.aider]
# enabled = true
# output_path_instructions = "AGENTS.md"
# output_path_config = ".aider.conf.yml"

# [agents.gemini-cli]
# enabled = true

# --- MCP Servers ---
# Define Model Context Protocol servers here. Two examples:
# 1. A stdio server (local executable)
# 2. A remote server (HTTP-based)

# [mcp_servers.example_stdio]
# command = "node"
# args = ["scripts/your-mcp-server.js"]
# env = { API_KEY = "replace_me" }

# Context7 MCP server, TBD vs ref.tools and NIA
[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
